trees/backtree/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'backtree'
urlpatterns = [
    # path('', views.hello),
    # path('lists/<pindex>', views.lists,name='lists'),
    url(r'^lists(?P<pIndex>[0-9]*)/$', views.lists, name='lists'),
    path('check/', views.checktree, name='check'),
    path('codes/', views.codes, name='codes'),
    path('user/', views.usertree, name='user'),
    path('structure', views.structure_edit, name='structure')
    # path('insert/', views.insert,name='insert'),

    # url('index/', views.lists, name='lists'),
    # url('index/', views.insert, name='insert'),
    # url('index/', views.hello),
]

trees/login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainmenu, name="login")
]

trees/maptree/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'maptree'
urlpatterns = [
    path('lists/', views.maplist, name='lists'),
    path('insert/', views.map_insert, name='insert')
    # path('lists/', mapview.as_view(), name="maptrees")
]

trees/trees/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('', include('login.urls')),
    path('back/', include('backtree.urls', namespace='backtree')),
    path('map/', include('maptree.urls', namespace='maptree')),
    path('admin/', admin.site.urls),
]

trees/login/models.py
from django.db import models

# Create your models here.

trees/login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render

def mainmenu(request):
    return render(request, "login.html")

# Create your views here.

trees/maptree/views.py
# Create your views here.
import json
from django.shortcuts import render, redirect
from django.utils.timezone import now
from . import models
from .models import TreeEntity, TreeUser
from django.db.models import Q
from django.forms.models import model_to_dict
from datetime import date, datetime
from django.http import JsonResponse


class ComplexEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime):
            return obj.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(obj, date):
            return obj.strftime('%Y-%m-%d')
        else:
            return json.JSONEncoder.default(self, obj)


def maplist(request):
    tree_point = models.TreeEntity.objects.all()
    # datas = []
    # datas['list'] = tree_point
    tree_id = []
    tree_entity_id = []
    tree_x = []
    tree_y = []
    # tree_pno = []
    tree_pname = []
    tree_regionid = []
    tree_company = []
    tree_place = []
    tree_rate = []
    # tree_recorderid = []
    # tree_createdate = []
    # tree_checkerid = []
    # tree_checktime = []

    # tree_altitude = []
    # tree_longtitude = []
    # tree_latitude = []

    # tree_height = []
    # tree_dbh = []
    # tree_date = []

    # tree_health = []

    # 传输数据到json
    for i in range(len(tree_point)):
        tree_x.append(tree_point[i].p_x)
        tree_y.append(tree_point[i].p_y)
        tree_entity_id.append(tree_point[i].entity_id)
        tree_id.append(tree_point[i].id)
        tree_rate.append(tree_point[i].rate)
        tree_place.append(tree_point[i].place)
        tree_pname.append(tree_point[i].pname)
        tree_company.append(tree_point[i].plant_company)
        tree_regionid.append(tree_point[i].region_id)

    # 查询
    keyword = request.POST.get('eids', '')
    keyword2 = request.POST.get('species', '')
    keyword3 = request.POST.get('places', '')
    results = TreeEntity.objects.filter(Q(entity_id__icontains=keyword) &
                                        Q(pname__icontains=keyword2) &
                                        Q(place__icontains=keyword3))
    list_results = []
    for result in results:
        dic = model_to_dict(result)
        list_results.append(dic)
    return render(request, 'maptree2.html', {'tree_x': json.dumps(tree_x, cls=ComplexEncoder),
                                             'tree_y': json.dumps(tree_y, cls=ComplexEncoder),
                                             'tree_entity_id': json.dumps(tree_entity_id, cls=ComplexEncoder),
                                             'tree_rate': json.dumps(tree_rate, cls=ComplexEncoder),
                                             'tree_place': json.dumps(tree_place, cls=ComplexEncoder),
                                             'tree_pname': json.dumps(tree_pname, cls=ComplexEncoder),
                                             'tree_id': json.dumps(tree_id, cls=ComplexEncoder),
                                             'region_id': json.dumps(tree_regionid, cls=ComplexEncoder),
                                             'tree_company': json.dumps(tree_company, cls=ComplexEncoder),
                                             'result': json.dumps(list_results, cls=ComplexEncoder)
                                             })


# def mapinsert(request):
#     treeofuser = models.TreeUser.objects.filter(checked=0)
#     list_usertree = []
#     for users in treeofuser:
#         dics = model_to_dict(users)
#         list_usertree.append(dics)
#     return render(request, 'mapinsert.html', {'usertree': json.dumps(list_usertree, cls=ComplexEncoder)})


def map_insert(request):
    if request.method == 'GET':
        treeofuser = models.TreeUser.objects.filter(checked=0)
        list_usertree = []
        for users in treeofuser:
            dics = model_to_dict(users)
            list_usertree.append(dics)

        lasttree = models.TreeEntity.objects.order_by('entity_id').last()
        lasteid = lasttree.entity_id
        new_id = lasteid + 1

        treeofsystem = models.TreeEntity.objects.all()
        tree_entities = []
        for tr in treeofsystem:
            diction = model_to_dict(tr)
            tree_entities.append(diction)

        mycode = models.Code.objects.filter(cname='树种')
        list_code = []
        for co in mycode:
            di = model_to_dict(co)
            list_code.append(di)
        return render(request, 'mapinsert.html', {'unchecked': json.dumps(list_usertree, cls=ComplexEncoder),
                                                  'last': lasteid, 'code': list_code, 'entity': tree_entities,
                                                  'new': new_id})
    elif request.method == "POST":
        id = models.TreeUser.objects.all().count() + 1
        lasttree = models.TreeUser.objects.exclude(Q(way=1) | Q(checked=1)).order_by('id').last()
        lasteid = lasttree.entity_id
        entity_id = request.POST.get("entity_id")
        if entity_id == '':
            entity_id = lasteid + 1
            print(entity_id)
        obj = models.TreeEntity.objects.filter(entity_id=entity_id).first()
        pno = request.POST.get("pno")
        if pno == '':
            if obj:
                pno = obj.pno
            else:
                pno = None
        pname = request.POST.get("pname")
        if pname == '':
            if obj:
                pname = obj.pname
            else:
                pname = None
        p_x = request.POST.get("p_x", None)
        p_y = request.POST.get("p_y", None)
        lng = request.POST.get("lng")
        if lng == '':
            if obj:
                lng = obj.longitude
            else:
                lng = None
        lat = request.POST.get("lat")
        if lat == '':
            if obj:
                lat = obj.latitude
            else:
                lat = None
        ualtitude = request.POST.get("altitude")
        if ualtitude == '':
            if obj:
                ualtitude = obj.altitude
            else:
                ualtitude = None
        height = request.POST.get("tree_height")
        if height == '':
            if obj:
                height = obj.height
            else:
                height = None
        dbh = request.POST.get("dbh")
        if dbh == '':
            if obj:
                dbh = obj.dbh
            else:
                dbh = None
        region_id = request.POST.get("region_id")
        if region_id == '':
            if obj:
                region_id = obj.region_id
            else:
                region_id = None
        plant_company = request.POST.get("plant_company")
        if plant_company == '':
            if obj:
                plant_company = obj.plant_company
            else:
                plant_company = None
        place = request.POST.get("place")
        if place == '':
            if obj:
                place = obj.place
            else:
                place = None
        rate = request.POST.get("rate")
        if rate == '':
            if obj:
                rate = obj.rate
            else:
                rate = None
        feature = request.POST.get("feature")
        if feature == '':
            if obj:
                feature = obj.feature
            else:
                feature = None
        usage = request.POST.get("usage")
        if usage == '':
            if obj:
                usage = obj.usage
            else:
                usage = None
        health = request.POST.get("health")
        if health == '':
            if obj:
                health = obj.health
            else:
                health = None
        introduction = request.POST.get("introduction")
        if introduction == '':
            if obj:
                introduction = obj.introduction
            else:
                introduction = None
        age = request.POST.get("age")
        if age == '':
            if obj:
                age = obj.age
            else:
                age = None
        gender = request.POST.get("gender")
        if gender == '':
            if obj:
                gender = obj.gender
            else:
                gender = None
        image_id = None
        recorder_id = 3
        create_date = now()
        if obj:
            way = 1
        else:
            way = 0
        checked = 0
        models.TreeUser.objects.create(id=id, entity_id=entity_id,
                                       pno=pno, pname=pname, p_x=p_x, p_y=p_y, longitude=lng, latitude=lat,
                                       altitude=ualtitude, height=height, dbh=dbh,
                                       region_id=region_id, plant_company=plant_company, plant_date=None,
                                       place=place, rate=rate, feature=feature, usage=usage, health=health,
                                       introduction=introduction, gender=gender, age=age, image_id=image_id,
                                       recorder_id=recorder_id, create_date=create_date, way=way, checked=checked
                                       )
        return redirect('maptree:insert')

trees/templates/back_check.html
{% load static %}
<!DOCTYPE html PUBLIC “-//W3C//DTD XHTML 1.0 Transitional//EN” “http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd”>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>单木数据管理系统</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/back.css' %}">

	<link rel="shortcut icon"  href="{% static 'images/favicon.ico' %}" type="image/x-icon">

    <script type="text/javascript" src="http://mat1.gtimg.com/libs/jquery/1.12.0/jquery.min.js" ></script>


	<script type="text/javascript">
	    function checktree(id,isEntered){	
	    	var index = id;
	    	var index2 = isEntered;
		    $.ajax({
			    url: '{% url "backtree:check" %}',
			    type: 'GET',
			    async: true,
			    data: {
			    	'num':index,
			    	'isEntered':index2,
			    },
			    success:function(result){
			    	alert("完成审核！");
			    },		    
			    error:function(){
			    	alert("审核失败！");
			    }			    
		    });
	    }
    </script>


	<style type="text/css">
        /*table {border-collapse: collapse;}*/
        #wanttree{
        	border-collapse: collapse;
        }


        #busi{            
            overflow-y: scroll;
        }

        #busi::-webkit-scrollbar-track
        {
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.1);
            background-color: #F5F5F5;
            border-radius: 10px;
        }

        #busi::-webkit-scrollbar
        {
            width: 5px;
            background-color: #F5F5F5;
        }

        #busi::-webkit-scrollbar-thumb
        {
            border-radius: 10px;
            background-color: #FFF;
            background-image: -webkit-gradient(linear,
                                       40% 0%,
                                       75% 84%,
                                       from(#4D9C41),
                                       to(#19911D),
                                       color-stop(.6,#54DE5D))
        }

        .button1{
	       background:linear-gradient(rgb(242 252 230),rgb(210 231 183));
           color: rgb(67 134 12);	
	       border-radius: 4px;
	       border:solid rgb(201 221 173)1px;
	       border-width: 0.1px;
           text-align: center;
           text-decoration: none;
           display: inline-block;
           font-size: 8px;  
           cursor: pointer;
           float: right;
           
        } 


        #entity_table{            
            overflow-y: scroll;
            height: 262px;
        }

        #entity_table::-webkit-scrollbar-track
        {
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.1);
            background-color: #F5F5F5;
            border-radius: 10px;
        }

        #entity_table::-webkit-scrollbar
        {
            width: 5px;
            background-color: #F5F5F5;
        }

        #entity_table::-webkit-scrollbar-thumb
        {
            border-radius: 10px;
            background-color: #FFF;
            background-image: -webkit-gradient(linear,
                                       40% 0%,
                                       75% 84%,
                                       from(#4D9C41),
                                       to(#19911D),
                                       color-stop(.6,#54DE5D))
        }

        #user_table{            
            overflow-y: scroll;
            height: 262px;
        }

        #user_table::-webkit-scrollbar-track
        {
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.1);
            background-color: #F5F5F5;
            border-radius: 10px;
        }

        #user_table::-webkit-scrollbar
        {
            width: 5px;
            background-color: #F5F5F5;
        }

        #user_table::-webkit-scrollbar-thumb
        {
            border-radius: 10px;
            background-color: #FFF;
            background-image: -webkit-gradient(linear,
                                       40% 0%,
                                       75% 84%,
                                       from(#4D9C41),
                                       to(#19911D),
                                       color-stop(.6,#54DE5D))
        }
      
        

    </style>

</head>

<body>
  <div class="center">
	<div class="header">
		<div class="inheader">
			<div class="first">
				<img src="{% static 'images/user.png' %}" style="padding-top:25px;padding-left:5px;position:relative;">

			</div>
			<div class="second">
				<p style="position:relative;float:left;text-align:center;">欢迎您-<br> Admin</p>

				<img src="{% static 'images/clock.png' %}" style="width:48px;height:48px;float:right;position:relative;margin-top:4px"  >
			</div>
			<div class="third">
				<div class="cms">
	        		<h1>单木数据管理系统</h1>
	        		<h2>TREE DATA MANAGEMENT</h2>
	        	</div>

			</div>
			<div class="fourth">
				<button class="button" style="margin-right:0px;margin-left:0px;" onclick="window.location.href='{% url 'maptree:lists' %}'" >⌂ 首页</button>
				<button class="button" style="margin-right:0px;margin-left:0px;" onclick="window.location.href='{% url 'backtree:structure' %}'" >↺ 库结构维护</button>
				<button class="button" style="margin-right:0px;margin-left:0px;">▶ 批创建</button>
				<button class="button" style="margin-right:0px;margin-left:0px;" onclick="window.location.href='{% url 'backtree:codes' %}'" >◀ 代码管理</button>
				<button class="button" style="margin-right:0px;margin-left:0px;" onclick="window.location.href='{% url 'backtree:check' %}'" >▤ 用户数据审核</button>
				<button class="button" style="margin-right:0px;margin-left:0px;" onclick="window.location.href='/login'" >ⓛ 退出</button>
			</div>
			<div class="fifth" id="date">
				    <script type="text/javascript">
                        setInterval(function(){
                        var date = new Date();
                        var year = date.getFullYear();    //获取当前年份
                        var mon = date.getMonth()+1;      //获取当前月份
                        var da = date.getDate();          //获取当前日
                        var day = date.getDay();          //获取当前星期几
                        var h = date.getHours();          //获取小时
                        var m = date.getMinutes();        //获取分钟
                        var s = date.getSeconds();        //获取秒
                        var d = document.getElementById('date');
          d.innerHTML=year+'年'+mon+'月'+da+'日'+'星期'+day+' '+h+':'+m+':'+s;
        },1000)
            </script>
			</div>
		</div>
	</div>
	<div class="middle">
		<div class="guide">
			<div class="manage">
				<img src="{% static 'images\cacula.png' %}" style="margin-left:5px;margin-right:3px;margin-top:5px;position:position:relative;float:left;">
				<div class="maop">
					<p>管理选项</p>
				</div>
				<div class="down">
					<img src="{% static 'images\time.png' %}" style="float:right;margin-top:5px;margin-right:2px;">
				</div>
			</div>
			<div class="option">
				<div class="op">
					<img src="{% static 'images\xitong.png' %}" style="margin-left:5px;margin-right:5px;margin-top:5px;">
				</div>
                 <div class="op">
					 <img src="{% static 'images\rizhi.png' %}" style="margin-left:5px;margin-right:5px;margin-top:5px;">
                 </div>
                 <div class="op">
					 <img src="{% static 'images\shuju.png' %}" style="margin-left:5px;margin-right:5px;margin-top:5px;">
                 </div>
                <a href="/back/lists{{pindex}}">后台系统数据</a>&nbsp;&nbsp;&nbsp;<a href="{% url 'backtree:user' %}">后台用户数据</a>&nbsp;&nbsp;&nbsp;<a href="{% url 'maptree:lists' %}">地图数据</a>
                 <div id="findzone" >
<!--  			        <form id="findback" method="post" >
                    {% csrf_token %}
                        <input type="integer" name="eid" placeholder="eid" style="width: 20px" >
                        <input type="charset" name="species" placeholder="树种" style="width: 42px" >
                        <input type="charset" name="places" placeholder="位置" style="width: 72px" >
                        <input  class="button1" type="submit" value="查询"  name="find" style="width: 35px">

                    </form> -->
                </div>
			</div>
			<div class="busi"  id="busi">
				<table class="ta" id="wanttree" border="1" background="{% static 'images\footer.jpg' %}" >
						<col align="center">
						</col>
						<caption >待审用户数据</caption>
						<thead>
						<tr style="background:linear-gradient(rgb(255 255 255),rgb(217 237 192));">
							<td>id</td>
							<td>eid</td>
							<td>树种</td>
						</tr>
						</thead>
						<tbody>
						{% for t in dischecked %}
						<tr>	
							<td width="25px">{{t.id}}</td>							
							<td width="50px">{{t.entity_id}}</td>
							<td width="100px">{{t.pname}}</td>
						</tr>
						{% endfor %}
						</tbody>
				</table>              
			</div>

		</div>
		<div class="work">
			
				<div class="tabl" id="entity_table">
					<table class="ta"  border="1"  >
						<col align="center">
						</col>
						<caption >系统数据</caption>
						<thead>
						<tr style="background:linear-gradient(rgb(255 255 255),rgb(217 237 192));">
							<td>选择</td>
							<td>序号</td>
							<td>实体编号</td>
							<td>树种编号</td>
							<td>树种名</td>
							<td>X坐标</td>
							<td>Y坐标</td>
							<td>邮编</td>
							<td>单位</td>
							<td>位置</td>
							<td>频率</td>
							<td>上传者</td>						
							<td>审核者</td>
							<td>审核时间</td>
							<td>编辑</td>
							<td>地图查看</td>
						</tr>
						</thead>
						<tbody>
						{% for d in list_entity %}
						<tr>
							<td><input type="checkbox" name=""></td>
							<td>{{d.id}}</td>
							<td>{{d.entity_id}}</td>
							<td>{{d.pno}}</td>
							<td>{{d.pname}}</td>
							<td>{{d.p_x}}</td>
							<td>{{d.p_y}}</td>
							<td>{{d.region_id}}</td>
							<td>{{d.plant_company}}</td>
							<td>{{d.place}}</td>
							<td>{{d.rate}}</td>
							<td>{{d.recorder_id}}</td>
							<td>{{d.checker_id}}</td>
							<td>{{d.check_time}}</td>
							<td><button class="button1" onclick="window.open('{% url 'maptree:insert' %}')">✎</button></td>
							<td><button class="button1" onclick="window.location.href='{% url 'maptree:lists' %}'" >地图查看</button></td>
						</tr>
						{% endfor %}
						</tbody>
					</table>
				</div>

				<div class="tabl" id="user_table">
					<table class="ta"  border="1"  >
						<col align="center">
						</col>
						<caption >用户数据</caption>
						<thead>
						<tr style="background:linear-gradient(rgb(255 255 255),rgb(217 237 192));">
							<td>选择</td>
							<td>序号</td>
							<td>实体编号</td>
							<td>树种编号</td>
							<td>树种名</td>
							<td>X坐标</td>
							<td>Y坐标</td>
							<td>邮编</td>
							<td>单位</td>
							<td>位置</td>
							<td>频率</td>
							<td>上传者</td>						
							<td>审核状态</td>
							<td>上传时间</td>
							<td>审核?</td>
							<td>通过?</td>
						</tr>
						</thead>
						<tbody>
						{% for d in list_user %}
						<tr>
							<td><input type="checkbox" name=""></td>
							<td>{{d.id}}</td>
							<td>{{d.entity_id}}</td>
							<td>{{d.pno}}</td>
							<td>{{d.pname}}</td>
							<td>{{d.p_x}}</td>
							<td>{{d.p_y}}</td>
							<td>{{d.region_id}}</td>
							<td>{{d.plant_company}}</td>
							<td>{{d.place}}</td>
							<td>{{d.rate}}</td>
							<td>{{d.recorder_id}}</td>
							<td>{{d.checked}}</td>
							<td>{{d.create_date}}</td>
							{% csrf_token %}
							{% if d.checked == 0 %}
							<td><button class="button1" name="{{ d.id }}" onclick="checktree(this.name,0)" >不通过</button></td>
							<td><button class="button1" name="{{ d.id }}" onclick="checktree(this.name,1)" >通过</button></td>
							{% elif d.checked == 1 %}
							    <td>已审核</td>
							    <td>未通过</td>
							{% else %}
							    <td>已审核</td>
							    <td>已通过</td>
							{% endif %}

						</tr>
						{% endfor %}
						</tbody>
					</table>
					
				</div>

			
		</div>
	</div>


	<div class="footer">
		<div class="fo1">
☐ 版本 2020V1.0
		</div>
		<div class="fo2">
			？
		</div>
	</div>
   </div>
</body>
</html>

trees/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>登录</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
	<div class="center" style="width:1000px;height:614px; background-image:url({% static 'images/1.jpg' %})">
	    <div class="login" >
	        <div class="header">
	        	<div class="inheader">
	        		<div class="inheadimg">
<!--	        			<img src="static/images/clock.png" >-->
                        <img src="{% static 'images/clock.png' %}" >
	        		</div>
	        		<div class="headtext1">	        			
	        			<div class="cms">	        				
	        				<h1>单木数据管理系统</h1>
	        				<tr></tr>
	        				<h2>TREE DATA MANAGEMENT SYSTEM</h2>
	        			</div>
	        		</div>
	        		<div class="headtext2">
	        			<h3>LOGIN 用户登录▶</h3>
	        		</div>
	        	</div>
	        </div>
	        <div class="main">
	        	<div class="lmain">	        		
	        		<div class="imag" align="center">
<!--	        			<img src="static/images/jiheti.png">	 -->
                        <img src="{% static 'images/jiheti.png' %}">
	        		</div>	        		
	        	</div>
	        	<div class="rmain">
	        		
	        		    <form action="{% url 'maptree:lists' %}">
	        			    <br>
	        			    <br>
	        			    &nbsp;&nbsp; 用户
	        			    <input type="text" name="user" >
	        			    <br>
	        			    <br>
	        			    &nbsp;&nbsp; 密码
	        			    <input type="password" name="pw" >
	        			    <br>
	        			    <br>
	        			    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	        			    <input type="submit" value="登陆">
	        			    <input type="submit" value="注册">
                        </form> 
	        		
	        	</div>
	        </div>
	        <div class="footer">
	        	<h4>
	        		☐ 版本 2020V1.0
	        	</h4>
	        </div>
	    </div>
	</div>
</body>
</html>

trees/templates/自定义信息窗表.html
<!DOCTYPE html>
<html>
<head>
	<title>信息窗表格设计</title>
</head>
<body>
    <table id="infw" border="1">
    	<tr>
    		<td>实体编号</td>
    		<td>4</td>
    	</tr>
    	<tr>
    		<td>树种名</td>
    		<td>银杏</td>
    	</tr>
    	<tr>
    		<td>GPS坐标x</td>
    		<td>113.0000000</td>
    	</tr>
    	<tr>
    		<td>GPS坐标y</td>
    		<td>40.0000000</td>
    	</tr>
    	<tr>
    		<td>分布位置</td>
    		<td>小南门内道路行道树</td>
    	</tr>
    	<tr>
    		<td>实体图片</td>
    		<td>
    			<img src="{% static 'images/tree.png' %}" style="width: 50px;height: 50px">    			
    		</td>
    	</tr>
    </table>
</body>
</html>

<!-- <img src="static/images/tree.png" style="width: 50px;height: 50px"> -->
<img src="{% static 'images/tree.png' %}" style="width: 50px;height: 50px"> 